@OrderPortal.Api_HostAddress = http://localhost:5147

GET {{OrderPortal.Api_HostAddress}}/weatherforecast/
Accept: application/json

###


POST {{OrderPortal.Api_HostAddress}}/api/demo/seed
Accept: application/json

###

GET {{OrderPortal.Api_HostAddress}}/api/demo/invoices
Accept: application/json

